import { readFileSync } from 'node:fs';
import { decodeSave } from '../../src/client/saves';
import { Sim } from '../../src/sim/sim';
const sim = Sim.fromSave(decodeSave(readFileSync(process.argv[2]!)));
const h = sim.state.economy.history;
const last = h.slice(-12);
const sum: Record<string, number> = {};
for (const m of last) for (const [k, v] of Object.entries(m.lines)) sum[k] = (sum[k] ?? 0) + v / last.length;
const pop = sim.state.totals.population;
for (const [k, v] of Object.entries(sum).sort((a, b) => b[1] - a[1])) console.log(k.padEnd(22), Math.round(v).toString().padStart(9), (v / pop).toFixed(2));
console.log('pop', pop, 'net', Math.round(Object.values(sum).reduce((a, b) => a + b, 0)));
